DROP TABLE IF EXISTS "subdict";
CREATE TABLE subdict (_id 			INTEGER PRIMARY KEY, chapter	 	VARCHAR(100), section	 	VARCHAR(100), xml			TEXT);
INSERT INTO "subdict" VALUES(1,'SubDictionary','acid','Noun. The drug LSD. Lysergic acid diethylamide. [Orig. U.S. 1960s]');
INSERT INTO "subdict" VALUES(2,'SubDictionary','aerated','Adj. Over-excited. Becoming obsolete, although still heard used by older generations. Often mispronounced as aeriated.');
INSERT INTO "subdict" VALUES(3,'SubDictionary','airhead','Noun. A stupid person. [Orig. U.S.]');
INSERT INTO "subdict" VALUES(4,'SubDictionary','anchors','Noun. Brakes. E.g.&quot;I slammed the anchors on and hit my head on the steering wheel.&quot;');
INSERT INTO "subdict" VALUES(5,'SubDictionary','antwacky','Adj. Old fashioned. Possibly from antique(y) or antiquated. E.g.&quot;Oh no way! I&apos;m not wearing those shoes, they&apos;re so antwacky.&quot; [Merseyside/West Lancashire use]');
INSERT INTO "subdict" VALUES(6,'SubDictionary','apeth','Noun. A pet name for a silly person. A shortening of daft apeth. Apeth, derived from haypneeworth (half a penny&apos;s worth) but pronounced ha&apos;p&apos;orth.');
INSERT INTO "subdict" VALUES(7,'SubDictionary','arris','Noun. Buttocks, &apos;arse&apos;. Convoluted Cockney rhyming slang for &apos;arse&apos;; Arris, an abbreviation of Aristotle, rhyming with bottle, and thereafter leading to bottle and glass rhyming with &apos;arse&apos;. Also aris.');
INSERT INTO "subdict" VALUES(8,'SubDictionary','backie','Noun. A pillion ride on a bycycle.');
INSERT INTO "subdict" VALUES(9,'SubDictionary','backy','Noun. Abb. of tobacco. Another variation is Backo.');
INSERT INTO "subdict" VALUES(10,'SubDictionary','baffies','Noun. Slippers. [Scottish use]');
INSERT INTO "subdict" VALUES(11,'SubDictionary','baked bean','Noun. The queen. Rhyming slang.');
INSERT INTO "subdict" VALUES(12,'SubDictionary','banko','Noun. Abb. of bank holiday (a national holiday).');
INSERT INTO "subdict" VALUES(13,'SubDictionary','cake-hole','Noun. The mouth. E.g.&quot;Shut your cake-hole and get on with your work.&quot; Cf. &apos;pie-hole&apos;.');
INSERT INTO "subdict" VALUES(14,'SubDictionary','cane','Verb. To hurt, to pain. E.g.&quot;It caned severely when I tried to walk on it, and I knew it was broken.&quot;');
INSERT INTO "subdict" VALUES(15,'SubDictionary','cardie','Noun. A cardigan. {Informal}');
INSERT INTO "subdict" VALUES(16,'SubDictionary','dancers','Noun. Stairs. Also, but less commonly, jolly dancers and molly dancers. [North-west use]');
INSERT INTO "subdict" VALUES(17,'SubDictionary','dead','Adv. Very, extremely. E.g.&quot;Our holiday was dead good.&quot;');
INSERT INTO "subdict" VALUES(18,'SubDictionary','faffer','Noun. A person who fusses, or dithers. See &apos;faff&apos;.');
INSERT INTO "subdict" VALUES(19,'SubDictionary','hammer','Verb. To take or do something to excess. E.g.&quot;I spent all yesterday hammering the booze and all last night throwing up.&quot;');
INSERT INTO "subdict" VALUES(20,'SubDictionary','keg','Verb. To pull down a person&apos;s trousers as a mischevious act. E.g.&quot;It was so funny; we kegged him on the high street in full view of all the Saturday shoppers.&quot;');
INSERT INTO "subdict" VALUES(21,'SubDictionary','kermit','Noun. The toilet. Rhyming slang, from Kermit the Frog, meaning &apos;bog&apos;. See &apos;bog&apos;.');
INSERT INTO "subdict" VALUES(22,'SubDictionary','mahusive','Adj. Immense, sizable, great. Probably from massive.');
INSERT INTO "subdict" VALUES(23,'SubDictionary','malarkey','Noun. Nonsense, foolishness. Also malarky. [Orig U.S.]');
INSERT INTO "subdict" VALUES(24,'SubDictionary','pair','Noun. A euphemism for a woman&apos;s breasts.');
INSERT INTO "subdict" VALUES(25,'SubDictionary','panto','Noun. Abb. of pantomine, being a theatrical show, mainly for children, and usually staged around the Christmas period. {informal}');
